### ISSUE TITLE
How to use Ajax?

### ISSUE THREAD

**Issue by jaboh** [jczic/MicroWebSrv#20]
Many thanks for making MicroWebSrv available!
I got a live web page update loop working with web sockets, but the real page I am trying to port to the esp32 uses Jquery Ajax (with web.py on a Raspberry Pi Zero). It would save me quite some work if I would not have to rewrite/debug the script for web sockets.
The browser developer window tells me that the script hangs in a send.
The server does not register any activity at all.
What am I doing wrong?
testajax.py:
[testajax.py.txt](https://github.com/jczic/MicroWebSrv/files/1821751/testajax.py.txt)
testajax.html:
[testajax.html.txt](https://github.com/jczic/MicroWebSrv/files/1821754/testajax.html.txt)

**Comment by jaboh** [comment]
I'm such an idiot: omitted the 'url: "/test" argument!
Works like a dream now, thanks for listening :-)

**Comment by jczic** [comment]
Yeah !
Cool and thank you for using this code 👍
