### ISSUE TITLE
Does it work on esp8266?

### ISSUE THREAD

**Issue by njXuanX** [jczic/MicroWebSrv#21]
A very good webserver for micropython, even with websocket and template!
My question is, does this powerful lightweight web server work on esp8266? After all, micropython offically support 8266, and 32 and 8266 using same basic MicroPython libraries. Or should I do some modify to make it works.
Thanks a lot!

**Comment by jczic** [comment]
Hello and thank you :')
I have never tested it on esp8266 but do you can do it ?

**Comment by njXuanX** [comment]
@jczic Seems dosent work, actually can not download the microWebSrv lib to 8266, I use uPycraft as IDE.
![1](https://user-images.githubusercontent.com/35806311/37970167-446c7810-3205-11e8-9a59-cd4e8a5b2132.png)

**Comment by jczic** [comment]
Yes ok, you have not enought RAM memory to load MicroWebSrv... It works fine with modules who have 4 SDRam extension.

**Comment by njXuanX** [comment]
@jczic Thanks a lot, still a very good project.

**Comment by jczic** [comment]
Thank you ! 👍
