### ISSUE TITLE
Memory importing MicroWebSrv on LoPy 1

### ISSUE THREAD

**Issue by jajberni** [jczic/MicroWebSrv#22]
When running the basic example, in the import statement:
`from microWebSrv import MicroWebSrv`

I get the following exception:
`MemoryError: memory allocation failed, allocating 56 bytes`

According to `print(gc.mem_free())` my free memory before the import is `57072`

I am trying this on a LoPy with firmware version '1.17.3.b1'

**Comment by jczic** [comment]
Hello,
Yes, it must be hosting and compiled in the firmware (/frozen) or turn under the OEM pycom devices with 4Mo of SDRAM.
