### ISSUE TITLE
html and js gzip support

### ISSUE THREAD

**Issue by JavierNR** [jczic/MicroWebSrv#30]
Hello, 

First of all, congrats for the great project and for sharing!.

I'm trying to make MicroWebSrv serve gzipped index and js files (just testing doing an app with react). But at the moment can't make it work.

I've modified microwebsrv.py file adding:
`"index.html.gz"` under _indexPages
And
`".gz"    : "application/gzip"` under _mimeTypes

I'm really novice, i'll investigate further, just asking if someone has better knowledge to help me

**Comment by jczic** [comment]
Hello,
If you want to serve .gz files, you can add directly the mime type to the list like that :
MicroWebSrv. _mimeTypes[".gz"] = "application/gzip"
That's works ?

**Comment by JavierNR** [comment]
Hello @jczic 
I've added gz mimeType but it downloads the file ("index.html.gz") instead of rendering the html page.
Tried also adding "index.html.gz" to _indexPages.

Maybe I'm not very clear before! Many thanks for your help!

![image](https://user-images.githubusercontent.com/1872120/40369110-91260a0a-5ddd-11e8-8b5b-df75197aea8f.png)

**Comment by jczic** [comment]
Yes, the browser receive a .gz and download it.
This web server (MicroWebSrv) doesn't have any function to unzip files.

**Comment by JavierNR** [comment]
Ah I see,, do you think it's possible to implement gz pages rendering? Or maybe there's some limit on pycom stack?

**Comment by jczic** [comment]
Unzip/GZ implementation doesn't exists on pycom modules.
It must be rewrited in mycropython or implemented in C on firmware directly ...
