### ISSUE TITLE
error throw out when init webserver on lobo ESP32 micropython

### ISSUE THREAD

**Issue by suli3** [jczic/MicroWebSrv#32]
hi jczic:
i meant to try the code below:

from microWebSrv import MicroWebSrv
mws = MicroWebSrv() # TCP port 80 and files in /flash/www
mws.Start()         # Starts server in a new thread

i got the error message when i import microWebSrv, is there any dependent library i didnt use or compiled with？Thanks..

>>> from microWebSrv import MicroWebSrv
Traceback (most recent call last):
File "<stdin>", line 1, in <module>

**Comment by suli3** [comment]
Sorry but i fixed it, i missed the WebSocket module when make FW, now the the web server could work. thanks.

**Comment by jczic** [comment]
😊
