### ISSUE TITLE
Webserver & GPIO

### ISSUE THREAD

**Issue by kebsont** [jczic/MicroWebSrv#34]
Hi, I just discover this microserver, but i don't find a way to interact with GPIO.

I mean, putting a button in my webpage, and interact with my pycom pin through this button.

**Comment by nevercast** [comment]
If the button posts to an endpoint then you would just use the normal Pycom APIs inside your route handler. So create an endpoint that handles a POST to /toggle, and then in that handler use the `Pin` class from `machine` to change the output of the GPIO. https://docs.pycom.io/chapter/firmwareapi/pycom/machine/Pin.html
