### ISSUE TITLE
No socket write when run in thread

### ISSUE THREAD

**Issue by curlyz** [jczic/MicroWebSrv#40]
Hi , is it weird that when the Start() run in main thread , everything work  , but if I do 
`start_new_thread(Start , ())`
 , there seem to be no socket._write() occur ! . 
Is there anyway to make it async ?

**Comment by jczic** [comment]
Hello @curlyz,
Why do you use start_new_thread for MicroWebSrv ?
It's already threaded if you want.
Or I don't understand ?
