### ISSUE TITLE
link css in html,browser 302 found.

### ISSUE THREAD

**Issue by ub3132003** [jczic/MicroWebSrv#69]
how to link css file in html .
thank

**Comment by ub3132003** [comment]
should I code a file server ?

**Comment by jczic** [comment]
Hello, do you have found?

**Comment by ub3132003** [comment]
the simple  solution that is return a css file witch browser url  request .
but I'd like to make a fileserver that I chould coding much less
| |
ub313
|
|
ub3132003@163.com
|
签名由网易邮箱大师定制
On 1/3/2020 13:46，J-Christophe Bos<notifications@github.com> wrote：

Hello, do you have found?

**Comment by jczic** [comment]
`.css` files are returned by the server as in the demo page with `style.css`.
Where is your problem exactly, I don't understand.
