### ISSUE TITLE
Chrome not load all files ?

### ISSUE THREAD

**Issue by straga** [jczic/MicroWebSrv#8]
Why Chrome, Opera not loading all files (index.html. style.css, bootstrap.css, jquery.js, app.js). Every F5 load only some files?

FireFox works.

**Comment by jczic** [comment]
Hi,
It's possible if MicroWebSrv process in no multi-thread mode.
Do you have try with multi-thread to True ?

**Comment by straga** [comment]
It ESP8266.

**Comment by jczic** [comment]
But it can accept one connection at the same time if it's not in multi-threading mode.

**Comment by straga** [comment]
ESP8266 not support _thread, or you meaning something also ?

**Comment by jczic** [comment]
I've never tested it on esp8266 but it works fine on ESP32 and Pycom modules.
It's strange that don't loads all files on your chrome but threads config is maybe the problem ?

**Comment by straga** [comment]
hm ESP8266 not have threads. Need write other Http server for ESP8266.

**Comment by straga** [comment]
I try write webserver for ESP8266 with timer without bloking. Runner run every 100ms for check connect. Load file by file.
https://www.youtube.com/edit?video_id=VdtNRpn-UfA
