### ISSUE TITLE
ImportError: cannot import name dupterm

### ISSUE THREAD

**Issue by BoKKeR** [jczic/MicroWebSrv#9]
`ImportError: cannot import name dupterm`

am I doing something wrong ? I am using the boot from the package

**Comment by jczic** [comment]
Hi,
Do not use the boot.py if you are not on a Pycom module and tell me if that's works.

**Comment by BoKKeR** [comment]
Managed to get it work. Another problem was that the main.py used by default `webPath="/flash/www"` instead of `webPath="/www"` for the esp32. After changing that hidden argument it just worked. Thanks for the help

**Comment by jczic** [comment]
Yep, /flash is for pycom :)
It's cool if all works for you 👍
